/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.primerapractica.Graficas;

import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class ApuestaManual extends javax.swing.JPanel {
    private panelPrincipal panel;
    private int [] apuestas = new int[10];
    /**
     * Creates new form ApuestaManual
     */
    public ApuestaManual(panelPrincipal panel) {
        this.panel = panel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c9 = new javax.swing.JLabel();
        c10 = new javax.swing.JLabel();
        p1 = new javax.swing.JComboBox<>();
        p2 = new javax.swing.JComboBox<>();
        p3 = new javax.swing.JComboBox<>();
        p4 = new javax.swing.JComboBox<>();
        p5 = new javax.swing.JComboBox<>();
        p6 = new javax.swing.JComboBox<>();
        p7 = new javax.swing.JComboBox<>();
        p8 = new javax.swing.JComboBox<>();
        p9 = new javax.swing.JComboBox<>();
        p10 = new javax.swing.JComboBox<>();
        confirmar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa el orden de entrada de los caballos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 81, 0, 58);
        add(jLabel1, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Lugar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 69, 0, 0);
        add(jLabel2, gridBagConstraints);

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setText("Primero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 69, 0, 0);
        add(c1, gridBagConstraints);

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setText("Segundo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 69, 0, 0);
        add(c2, gridBagConstraints);

        c3.setBackground(new java.awt.Color(255, 255, 255));
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setText("Tercero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 69, 0, 0);
        add(c3, gridBagConstraints);

        c4.setBackground(new java.awt.Color(255, 255, 255));
        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.setText("Cuarto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 69, 0, 0);
        add(c4, gridBagConstraints);

        c5.setBackground(new java.awt.Color(255, 255, 255));
        c5.setForeground(new java.awt.Color(255, 255, 255));
        c5.setText("Quinto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 69, 0, 0);
        add(c5, gridBagConstraints);

        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.setText("Sexto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 69, 0, 0);
        add(c6, gridBagConstraints);

        c7.setBackground(new java.awt.Color(255, 255, 255));
        c7.setForeground(new java.awt.Color(255, 255, 255));
        c7.setText("Septimo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 69, 0, 0);
        add(c7, gridBagConstraints);

        c8.setBackground(new java.awt.Color(255, 255, 255));
        c8.setForeground(new java.awt.Color(255, 255, 255));
        c8.setText("Octavo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 69, 0, 0);
        add(c8, gridBagConstraints);

        c9.setBackground(new java.awt.Color(255, 255, 255));
        c9.setForeground(new java.awt.Color(255, 255, 255));
        c9.setText("Noveno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 69, 0, 0);
        add(c9, gridBagConstraints);

        c10.setBackground(new java.awt.Color(255, 255, 255));
        c10.setForeground(new java.awt.Color(255, 255, 255));
        c10.setText("Decimo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 69, 0, 0);
        add(c10, gridBagConstraints);

        p1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 96, 0, 58);
        add(p1, gridBagConstraints);

        p2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "1", "3", "4", "5", "6", "7", "8", "9", "10" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(p2, gridBagConstraints);

        p3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "1", "2", "4", "5", "6", "7", "8", "9", "10" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(p3, gridBagConstraints);

        p4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "1", "2", "3", "5", "6", "7", "8", "9", "10" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(p4, gridBagConstraints);

        p5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "1", "2", "3", "4", "6", "7", "8", "9", "104" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(p5, gridBagConstraints);

        p6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "1", "2", "3", "4", "5", "7", "8", "9", "104" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(p6, gridBagConstraints);

        p7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "1", "2", "3", "4", "5", "6", "8", "9", "10" }));
        p7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(p7, gridBagConstraints);

        p8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "1", "2", "3", "4", "5", "6", "7", "9", "10" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(p8, gridBagConstraints);

        p9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9", "1", "2", "3", "4", "5", "6", "7", "8", "10" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(p9, gridBagConstraints);

        p10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(p10, gridBagConstraints);

        confirmar.setBackground(new java.awt.Color(51, 255, 255));
        confirmar.setText("Confirma Lugares");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 27;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 43, 0);
        add(confirmar, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Numero de caballo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 58);
        add(jLabel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void p7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p7ActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        
        apuestas [0] = Integer.parseInt((String) p1.getSelectedItem());
        apuestas [1] = Integer.parseInt((String) p2.getSelectedItem());
        apuestas [2] = Integer.parseInt((String) p3.getSelectedItem());
        apuestas [3] = Integer.parseInt((String) p4.getSelectedItem());
        apuestas [4] = Integer.parseInt((String) p5.getSelectedItem());
        apuestas [5] = Integer.parseInt((String) p6.getSelectedItem());
        apuestas [6] = Integer.parseInt((String) p7.getSelectedItem());
        apuestas [7] = Integer.parseInt((String) p8.getSelectedItem());
        apuestas [8] = Integer.parseInt((String) p9.getSelectedItem());
        apuestas [9] = Integer.parseInt((String) p10.getSelectedItem());
        if(panel.getFunciones().getLista().verificarRepeticion(apuestas)){
            JOptionPane.showMessageDialog(null, "Cada lugar lo debe de ocupar un caballo diferente");
        }
        else{
            panel.getFunciones().getLista().calcResult(apuestas);
            panel.getIzquierda().setVisible(false);
        }
    }//GEN-LAST:event_confirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c10;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel c9;
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> p1;
    private javax.swing.JComboBox<String> p10;
    private javax.swing.JComboBox<String> p2;
    private javax.swing.JComboBox<String> p3;
    private javax.swing.JComboBox<String> p4;
    private javax.swing.JComboBox<String> p5;
    private javax.swing.JComboBox<String> p6;
    private javax.swing.JComboBox<String> p7;
    private javax.swing.JComboBox<String> p8;
    private javax.swing.JComboBox<String> p9;
    // End of variables declaration//GEN-END:variables

    public int[] getApuestas() {
        return apuestas;
    }

    public void setApuestas(int[] apuestas) {
        this.apuestas = apuestas;
    }

}
